# Generated by Django 2.0.1 on 2018-01-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180127_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='RescueRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.IntegerField()),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=20)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=20)),
                ('message', models.CharField(max_length=280)),
            ],
        ),
        migrations.DeleteModel(
            name='ClusterPacket',
        ),
        migrations.AddField(
            model_name='keyword',
            name='city',
            field=models.CharField(default='Houston', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyword',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyword',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyword',
            name='state',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
