# Generated by Django 2.0.1 on 2018-01-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180127_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescuerequest',
            name='time',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
